### ISSUE TITLE
Clarify MSRV

### ISSUE THREAD

**Issue by rhysd** [1Password/arboard#120]
What is the minimum supported Rust version for this crate?

If possible, setting [`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) metadata is helpful for checking MSRV.

**Comment by complexspaces** [comment]
Hey there,

I haven't determined a MSRV yet for `arboard` since I, personally, don't generally see the value in MSRVs. I just don't use features I know are new to avoid breaking user's builds.

With that said if its a request to implement one, I don't mind. Does Rust 1.61 (first released May 19, 2022) work for you? That is also `image`'s.

**Comment by rhysd** [comment]
Hi, thanks for the quick reply.

> I haven't determined a MSRV yet for arboard since I, personally, don't generally see the value in MSRVs.

I haven't explained why it is important for me. I'm developing a library and I'm thinking to use this crate as dependency of the library. The MSRV of a library is bound by its dependencies. So I wanted to clarify MSRV of this crate.

> With that said if its a request to implement one, I don't mind. Does Rust 1.61 (first released May 19, 2022) work for you? That is also image's.

Yes, it works perfectly for me :+1:. I created this issue to clarify MSRV. But I have no request about what Rust version this crate should support.

**Comment by complexspaces** [comment]
This is now implemented, and retroactively applies to the latest 3.3.0 release.
