### ISSUE TITLE
[x-issue] Potential EoP in Windows clipboard libraries (MS15-097)

### ISSUE THREAD

**Issue by oberrich** [1Password/arboard#145]
See [Potential EoP in Windows clipboard libraries (MS15-097)](https://github.com/oberrich/x-issues/issues/1) for discussion.

**Comment by oberrich** [comment]
**Proposed fix**: Upgrade to [`clipboard-win = "5.3.1"`](https://crates.io/crates/clipboard-win) (fixed in https://github.com/DoumanAsh/clipboard-win/commit/9894a702267758a2eab05fc364f5fd3c4f30f2be)

**Comment by complexspaces** [comment]
Hey there, thank you for bringing this up. This is a very weird vulnerability, so hopefully no one was impacted by it. I've opened #146 to raise the version used in this repositories lockfile but downstream users need to update `clipboard-win` in their own lockfiles (if they have one) using `cargo update`. Its not worth `arboard` pushing a stricter version because of how poorly Cargo handles version range and pinning requirements.
