### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by martin-t** [1Password/arboard#26]
I noticed in the readme that you plan to deprecate the project. I don't know how many users it has or if there are alternatives but i'd like to suggest to you that you should instead attempt to find new maintainers. The best places for that are probably [r/rust](https://old.reddit.com/r/rust/) and [This week in Rust](https://this-week-in-rust.org/blog/2021/10/20/this-week-in-rust-413/)'s Call for Participation section, maybe also https://users.rust-lang.org/.

You can create a GitHub organization and add interested people into it. You could also attempt to transfer ownership to an organization that already depends on it like https://github.com/alacritty. As a last resort, you can use [Rust Bus](https://users.rust-lang.org/t/bus-factor-1-for-crates/17046) so the crate can find new owners and save people the maintenance burden of looking for a new fork and switching to it.

**Comment by ArturKovacs** [comment]
No takers?

**Comment by mathieulj** [comment]
I'm sorry I have not spoken up about this before, I was rather hoping that a community member would take the lead on this. We use arboard at work and we would be willing to take ownership of the project under our wing but we hesitated to do so in part because we do not use all the features/platforms and did not want people getting the idea that we are officially supporting those without making any use of them ourselves. I have spoken with a few people here and the consensus is that we could take over ownership if we were to add the following disclaimer:

```
Please note that this is not an official <my employer> product. Feature requests will be considered on a volunteer contribution basis. Issues not affecting our own use of this crate may not get immediate attention but we will happily accept  pull requests from contributors willing to work with us to get it merged.
```

What are your thoughts on the matter?

**Comment by ArturKovacs** [comment]
I'd be glad to take that offer. I just want to remain a maintainer for a little while at least. What's the organization or account I should transfer to?

**Comment by PurpleBooth** [comment]
Just to keep you updated: I had a think about this over the weekend and decided that this was a bit above my current comfort level, I just don't know enough about the domain to be able to answer the questions/things that are in the current pull requests.

**Comment by mathieulj** [comment]
I'm glad to hear you want to remain a part of the project. What did you have in mind for the required level of permissions and level of interactions? I honestly feel a little bad asking the question but our IT & dev ops need to verify we can set things up correctly. Things get complicated for external users [at levels above Triage](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role).

For the transfer itself, we will have to go through an intermediate user who is an employee because of [Github permission requirements for transferring to an organisation](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#about-repository-transfers).

**Comment by ArturKovacs** [comment]
This might already be obvious but just in case: the repository must remain public.

I'd like to have "Write" access because I'd like to be able to merge PRs.

Making an intermediate transfer is fine with me.

**Comment by ArturKovacs** [comment]
@PurpleBooth thanks for investing your time into this! I often feel like I don't know enough about the domain either.

**Comment by mathieulj** [comment]
I'm so sorry to keep you waiting. I hope you will understand but I am trying to get confirmation and pre-approval internally before accepting any transfers and other events/work has kept those teams really busy recently. I don't want to accept a transfer until I am sure that no policy or lack of approval would prevent us from assigning you the permissions you are comfortable with. 

> This might already be obvious but just in case: the repository must remain public.
I feel I should address this one directly because it is a pretty important point. We have no desire to limit access to this project and we want it to remain publicly accessible for the benefit of all.

**Comment by ArturKovacs** [comment]
Thank you for your considerate approach @mathieulj

**Comment by mathieulj** [comment]
So it seems I have to apologize again and I must take full responsibility. This issue has fallen through the cracks for me while I had blinders on trying to get something else sorted out. We have gotten the pre-approvals internally so we can proceed without worry of something preventing us from giving you your requested permissions after the transfer.

With that said, we are coming up on the holiday season where a lot of staff will be out on paid leave. Would you prefer we wait until the second week of January to do the transfer? This would avoid possible delays between the transfer starting and getting your write access on the transferred project in our organization.

**Comment by ArturKovacs** [comment]
It's alright. I'm grateful that your organisation takes this over.

> Would you prefer we wait until the second week of January to do the transfer? This would avoid possible delays between the transfer starting and getting your write access 

Yes in that case I prefer to start it in January. Have a great holiday!

**Comment by mathieulj** [comment]
Thank you, and same to you!

**Comment by complexspaces** [comment]
For anyone who is following along with this issue, the transfer to 1Password has been completed. We'll be helping to passively improve and maintain the crate going forward. We should have some contribution guidelines up soon that cover it better soon 😃.
