### ISSUE TITLE
The copied data isn't available after the program exits on X11

### ISSUE THREAD

**Issue by ArturKovacs** [1Password/arboard#39]
As was described at https://github.com/1Password/arboard/issues/37#issuecomment-1072407160

**Comment by ArturKovacs** [comment]
@kjvalencik could you paste the example code and describe how to reproduce the issue?

**Comment by guihkx** [comment]
Wait, isn't this by design on X11, though? 🤔 

I remember having to deal with this issue when I started Linux, and the response to this was always: "it's by design, use a clipboard manager".

To be fair, this was more than 8 years ago, so things could have changed now...

Also, this doesn't seem to affect all desktop environments. For instance, on GNOME, it appears that they have implemented a clipboard manager directly in their compositor (https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/320), which I assume, is there to keep the clipboard content persistent, like on Windows.

So, running @kjvalencik's  last example, the clipboard contents are actually preserved on my machine (by the way, there's a `;` at the end of line 3).

- Arch Linux
- GNOME 41.5
- X11 session

**Comment by kjvalencik** [comment]
@guihkx That's interesting! I'm on a somewhat older version, Gnome 3.36.8; however, that merge request was added in 3.34 and should be present on my system. Installing gpaste did not seem to fix it.

So maybe it's not a bug in `arboard` and just a limitation of X11 and other software versions.

**Comment by guihkx** [comment]
Hmm... Aren't you using Linux Mint, though?

As far as I'm aware, Mint only offers 3 desktop environments: Cinnamon, MATE and XFCE. They all have different window managers/compositors, and none of them uses mutter, from GNOME.

* Cinnamon: [Muffin](https://github.com/linuxmint/muffin)
* MATE: [Marco](https://github.com/mate-desktop/marco)
* XFCE: [xfwm4](https://gitlab.xfce.org/xfce/xfwm4)
