### ISSUE TITLE
[windows] writing the empty string and reading it back causes panic

### ISSUE THREAD

**Issue by jabbalaci** [1Password/arboard#64]
Under Windows, if I write the empty string on the clipboard (clear it), I expect that if I read it back, I get again the empty string. But in this case, `clipboard.get_text()` panics. The error message is the following:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ContentNotAvailable - "The clipboard contents were not available in the requested format or the clipboard is empty."'
```

The clipboard is empty, true, but shouldn't it return the empty string in this case?

**Comment by complexspaces** [comment]
Hey there @jabbalaci,

Are you unwrapping an error somewhere in your own code, or is this coming from inside `arboard`? I don't think we have any panics in `arboard` which would cause this. 

I believe that the inconsistency here is coming from the crate that we use for clipboard operations. It [skips making any system calls](https://github.com/DoumanAsh/clipboard-win/blob/master/src/raw.rs#L332-L335) when it sees the data is an empty string. It makes sense to do this because otherwise you'd need to make a zero-sized global allocation, etc. While its a little weird, I think it still matches up with the docs for `Error::ContentNotAvailable`.

I'd recommend switching your code to use `.unwrap_or_default()` if you want this empty string behavior.

**Comment by jabbalaci** [comment]
Thanks! I contacted the author of clipboard-win, he made a patch. I think he will publish a new release soon.

**Comment by complexspaces** [comment]
Thanks for bringing that upstream for consideration. Given that we don't pin a specific version of `clipboard-win`, but just a minimum, you should be able to transparently get these changes by running `cargo update -p clipboard-win` in your project. Closing this as done.
